# Generated by Django 3.0.8 on 2020-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/pictures/'),
        ),
    ]
